### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KamiTopalyan** [KamiTopalyan/IdealabProject#1]
- [x] Create a view for approved orders
- [x] Assign a order number to all orders created (5 digits)
- [x] Add a state to indicate if an order has been bought set by the admin user
- [ ] A method of exporting everything to a google sheet or a .cvs file
